set_property SRC_FILE_INFO {cfile:/home/gbortola/CERN_Workspace/GitHub/100G-verilog-RoCEv2-lite/example/VCU118/fpga_100g/fpga/fpga.gen/sources_1/ip/cmac_gty_full/synth/cmac_gty_full.xdc rfile:../fpga/fpga.gen/sources_1/ip/cmac_gty_full/synth/cmac_gty_full.xdc id:1 order:EARLY scoped_inst:qsfp1_cmac_inst/gty_ch_1/xcvr_gty_com.cmac_gty_full_inst/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/gbortola/CERN_Workspace/GitHub/100G-verilog-RoCEv2-lite/example/VCU118/fpga_100g/fpga/fpga.gen/sources_1/ip/cmac_gty_full/synth/cmac_gty_full.xdc rfile:../fpga/fpga.gen/sources_1/ip/cmac_gty_full/synth/cmac_gty_full.xdc id:2 order:EARLY scoped_inst:qsfp2_cmac_inst/gty_ch_1/xcvr_gty_com.cmac_gty_full_inst/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/gbortola/CERN_Workspace/GitHub/100G-verilog-RoCEv2-lite/example/VCU118/fpga_100g/fpga/fpga.gen/sources_1/ip/cmac_gty_channel/synth/cmac_gty_channel.xdc rfile:../fpga/fpga.gen/sources_1/ip/cmac_gty_channel/synth/cmac_gty_channel.xdc id:3 order:EARLY scoped_inst:qsfp1_cmac_inst/gty_ch_2/xcvr_gty.cmac_gty_channel_inst/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/gbortola/CERN_Workspace/GitHub/100G-verilog-RoCEv2-lite/example/VCU118/fpga_100g/fpga/fpga.gen/sources_1/ip/cmac_gty_channel/synth/cmac_gty_channel.xdc rfile:../fpga/fpga.gen/sources_1/ip/cmac_gty_channel/synth/cmac_gty_channel.xdc id:4 order:EARLY scoped_inst:qsfp1_cmac_inst/gty_ch_3/xcvr_gty.cmac_gty_channel_inst/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/gbortola/CERN_Workspace/GitHub/100G-verilog-RoCEv2-lite/example/VCU118/fpga_100g/fpga/fpga.gen/sources_1/ip/cmac_gty_channel/synth/cmac_gty_channel.xdc rfile:../fpga/fpga.gen/sources_1/ip/cmac_gty_channel/synth/cmac_gty_channel.xdc id:5 order:EARLY scoped_inst:qsfp1_cmac_inst/gty_ch_4/xcvr_gty.cmac_gty_channel_inst/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/gbortola/CERN_Workspace/GitHub/100G-verilog-RoCEv2-lite/example/VCU118/fpga_100g/fpga/fpga.gen/sources_1/ip/cmac_gty_channel/synth/cmac_gty_channel.xdc rfile:../fpga/fpga.gen/sources_1/ip/cmac_gty_channel/synth/cmac_gty_channel.xdc id:6 order:EARLY scoped_inst:qsfp2_cmac_inst/gty_ch_2/xcvr_gty.cmac_gty_channel_inst/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/gbortola/CERN_Workspace/GitHub/100G-verilog-RoCEv2-lite/example/VCU118/fpga_100g/fpga/fpga.gen/sources_1/ip/cmac_gty_channel/synth/cmac_gty_channel.xdc rfile:../fpga/fpga.gen/sources_1/ip/cmac_gty_channel/synth/cmac_gty_channel.xdc id:7 order:EARLY scoped_inst:qsfp2_cmac_inst/gty_ch_3/xcvr_gty.cmac_gty_channel_inst/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/gbortola/CERN_Workspace/GitHub/100G-verilog-RoCEv2-lite/example/VCU118/fpga_100g/fpga/fpga.gen/sources_1/ip/cmac_gty_channel/synth/cmac_gty_channel.xdc rfile:../fpga/fpga.gen/sources_1/ip/cmac_gty_channel/synth/cmac_gty_channel.xdc id:8 order:EARLY scoped_inst:qsfp2_cmac_inst/gty_ch_4/xcvr_gty.cmac_gty_channel_inst/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/gbortola/CERN_Workspace/GitHub/100G-verilog-RoCEv2-lite/example/VCU118/fpga_100g/fpga/fpga.gen/sources_1/ip/vio_throughput/vio_throughput.xdc rfile:../fpga/fpga.gen/sources_1/ip/vio_throughput/vio_throughput.xdc id:9 order:EARLY scoped_inst:core_inst/RoCE_minimal_stack_512_instance/VIO_roce_throughput} [current_design]
set_property SRC_FILE_INFO {cfile:/home/gbortola/CERN_Workspace/GitHub/100G-verilog-RoCEv2-lite/example/VCU118/fpga_100g/fpga/fpga.gen/sources_1/ip/vio_retrans_debug/vio_retrans_debug.xdc rfile:../fpga/fpga.gen/sources_1/ip/vio_retrans_debug/vio_retrans_debug.xdc id:10 order:EARLY scoped_inst:core_inst/RoCE_minimal_stack_512_instance/RoCE_retransmission_module_instance/VIO_retrans_debug} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {qsfp1_cmac_inst/gty_ch_1/xcvr_gty_com.cmac_gty_full_inst/inst/gen_gtwizard_gtye4_top.cmac_gty_full_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_pwrgood_delay_inst[0].delay_powergood_inst/gen_powergood_delay.pwr_on_fsm_reg/Q}]
set_property src_info {type:SCOPED_XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {qsfp2_cmac_inst/gty_ch_1/xcvr_gty_com.cmac_gty_full_inst/inst/gen_gtwizard_gtye4_top.cmac_gty_full_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_pwrgood_delay_inst[0].delay_powergood_inst/gen_powergood_delay.pwr_on_fsm_reg/Q}]
set_property src_info {type:SCOPED_XDC file:3 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {qsfp1_cmac_inst/gty_ch_2/xcvr_gty.cmac_gty_channel_inst/inst/gen_gtwizard_gtye4_top.cmac_gty_channel_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_pwrgood_delay_inst[0].delay_powergood_inst/gen_powergood_delay.pwr_on_fsm_reg/Q}]
set_property src_info {type:SCOPED_XDC file:4 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {qsfp1_cmac_inst/gty_ch_3/xcvr_gty.cmac_gty_channel_inst/inst/gen_gtwizard_gtye4_top.cmac_gty_channel_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_pwrgood_delay_inst[0].delay_powergood_inst/gen_powergood_delay.pwr_on_fsm_reg/Q}]
set_property src_info {type:SCOPED_XDC file:5 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {qsfp1_cmac_inst/gty_ch_4/xcvr_gty.cmac_gty_channel_inst/inst/gen_gtwizard_gtye4_top.cmac_gty_channel_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_pwrgood_delay_inst[0].delay_powergood_inst/gen_powergood_delay.pwr_on_fsm_reg/Q}]
set_property src_info {type:SCOPED_XDC file:6 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {qsfp2_cmac_inst/gty_ch_2/xcvr_gty.cmac_gty_channel_inst/inst/gen_gtwizard_gtye4_top.cmac_gty_channel_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_pwrgood_delay_inst[0].delay_powergood_inst/gen_powergood_delay.pwr_on_fsm_reg/Q}]
set_property src_info {type:SCOPED_XDC file:7 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {qsfp2_cmac_inst/gty_ch_3/xcvr_gty.cmac_gty_channel_inst/inst/gen_gtwizard_gtye4_top.cmac_gty_channel_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_pwrgood_delay_inst[0].delay_powergood_inst/gen_powergood_delay.pwr_on_fsm_reg/Q}]
set_property src_info {type:SCOPED_XDC file:8 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {qsfp2_cmac_inst/gty_ch_4/xcvr_gty.cmac_gty_channel_inst/inst/gen_gtwizard_gtye4_top.cmac_gty_channel_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_pwrgood_delay_inst[0].delay_powergood_inst/gen_powergood_delay.pwr_on_fsm_reg/Q}]
current_instance core_inst/RoCE_minimal_stack_512_instance/VIO_roce_throughput
set_property src_info {type:SCOPED_XDC file:9 line:66 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id CDC-4 -from [get_pins -filter {REF_PIN_NAME=~C} -of_objects [get_cells -hierarchical -filter {NAME =~ "*probe_in_reg_reg*"}]]  -to [get_pins -filter {REF_PIN_NAME=~D} -of_objects [get_cells -hierarchical -filter {NAME =~ "*data_int_sync1_reg*"}]]  -user "vio" -description {The path has combinational circuit. But from hardware prospective the design works perfectly and the signals crossing happen after a very long time from the source has the value.} -tags "1050886" -scope -internal
set_property src_info {type:SCOPED_XDC file:9 line:67 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id CDC-1 -from [get_pins -filter {REF_PIN_NAME=~C} -of_objects [get_cells -hierarchical -filter { NAME =~  "*Hold_probe_in*" &&  IS_SEQUENTIAL } ]]  -to [get_pins -filter {REF_PIN_NAME=~CE} -of_objects [get_cells -hierarchical -filter { NAME =~  "*PROBE_IN_INST/probe_in_reg*" && IS_SEQUENTIAL} ]]  -user "vio" -description {The path has combinational circuit. But from hardware prospective the design works perfectly and the signals crossing happen after a very long time from the source has the value.} -tags "1050886" -scope -internal
current_instance
current_instance core_inst/RoCE_minimal_stack_512_instance/RoCE_retransmission_module_instance/VIO_retrans_debug
set_property src_info {type:SCOPED_XDC file:10 line:66 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id CDC-4 -from [get_pins -filter {REF_PIN_NAME=~C} -of_objects [get_cells -hierarchical -filter {NAME =~ "*probe_in_reg_reg*"}]]  -to [get_pins -filter {REF_PIN_NAME=~D} -of_objects [get_cells -hierarchical -filter {NAME =~ "*data_int_sync1_reg*"}]]  -user "vio" -description {The path has combinational circuit. But from hardware prospective the design works perfectly and the signals crossing happen after a very long time from the source has the value.} -tags "1050886" -scope -internal
set_property src_info {type:SCOPED_XDC file:10 line:67 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id CDC-1 -from [get_pins -filter {REF_PIN_NAME=~C} -of_objects [get_cells -hierarchical -filter { NAME =~  "*Hold_probe_in*" &&  IS_SEQUENTIAL } ]]  -to [get_pins -filter {REF_PIN_NAME=~CE} -of_objects [get_cells -hierarchical -filter { NAME =~  "*PROBE_IN_INST/probe_in_reg*" && IS_SEQUENTIAL} ]]  -user "vio" -description {The path has combinational circuit. But from hardware prospective the design works perfectly and the signals crossing happen after a very long time from the source has the value.} -tags "1050886" -scope -internal
